os:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - git clone https://github.com/ignitionrobotics/ign-cmake
  - cd ign-cmake
  - git checkout ign-cmake3
  - md build
  - cd build
  - cmake .. -DBUILD_TESTING:BOOL=False
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-WX"
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
  # Build the examples to make sure that find_package(ignition-math* REQUIRED) works
  - cd ../examples
  - md build 
  - cd build
  - cmake ..
  - cmake --build . --config %CONFIGURATION% 
  - cd ..
  
