%module "math"
%include Angle.i
%include GaussMarkovProcess.i
%include Rand.i
%include Vector2.i
%include Vector3.i
%include Vector4.i
%include Quaternion.i
%include Pose3.i
%include Matrix3.i
%include Matrix4.i
