%module "math"
%include Angle.i
%include GaussMarkovProcess.i
%include Rand.i
%include Vector2.i
%include Vector3.i
%include Vector4.i
%include Pose3.i
%include Quaternion.i
%include Line2.i
%include Line3.i
%include Matrix3.i
%include Matrix4.i
%include PID.i
%include SemanticVersion.i
%include SignalStats.i
%include Temperature.i
%include Triangle.i
