name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-math[0-9]'
      - 'gz-math[0-9]'
      - 'main'

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@focal
        with:
          codecov-enabled: true
          doxygen-enabled: true
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@jammy
