name: Ubuntu CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@chapulina/ci_dir
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@chapulina/focal
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
